use_frameworks!

source 'http://ph.benemind.com/diffusion/SPEC/emspecs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'MSAppModuleWebApp_Example' do
    #  pod 'MSAppModuleWebApp/WebViewController', :path => '../'
    #pod 'EMSpeed', :path => '../../../components/emspeed'
    pod 'MSAppModuleWebApp', :path => '../'
    pod 'UIImage-Helpers'
    pod 'MSThemeModuleCommon', '~> 1.0.0-beta.13'
    pod 'MSAppModuleShare/JSBridgeModuleShare', :path => '../../msappmoduleshare/'

    target 'MSAppModuleWebApp_Tests' do
        #  pod 'MSAppModuleWebApp/WebViewController', :path => '../'
        
        #  pod 'Specta'
        #  pod 'Expecta'
    end

end

