use_frameworks!

source 'http://ph.benemind.com/diffusion/SPEC/emspecs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'MSAppModuleWebApp_Example' do
    #  pod 'MSAppModuleWebApp/WebViewController', :path => '../'
    #pod 'EMSpeed', :path => '../../../components/emspeed'
    pod 'MSAppModuleWebApp', :path => '../'

end

target 'MSAppModuleWebApp_Tests' do
    #  pod 'MSAppModuleWebApp/WebViewController', :path => '../'
  pod 'MSAppModuleWebApp', :path => '../'

#  pod 'Specta'
#  pod 'Expecta'
end
